apiVersion: apps/v1
kind: Deployment
metadata:
   name: webapp
spec:
   strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 25%

   replicas: 5
   selector:    
    matchLabels:
     app: webapp
   template:
      metadata:
        labels:
          app: webapp
      spec:
       containers:
        - name: webapp
          image: ranjarat/webtest
          imagePullPolicy: Always
          ports:
          - containerPort: 80
---

apiVersion: v1
kind: Service                             
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  ports:
    - port: 80                               
      targetPort: 80                    
  selector:
    app: webapp                    
  type: LoadBalancer    